version: '3.7'

services:
  vpn:
    image: dperson/openvpn-client
      cap_add:
        - net_admin
      devices:
        - /dev/net/tun
      volumes:
        - openvpn:/vpn
      tmpfs:
        - /run
        - /tmp
      environment:
        TZ: 'America/New_York'
        DNS: 'true'
        FIREWALL: 'true'

  deluged:
    image: keschrich/deluged:1.3.15-1
    depends_on:
      - vpn
    network_mode: service:vpn
    volumes:
      - deluged-config:/config
      - data:/data
    environment:
      TZ: 'America/New_York'
      DELUGE_ALLOW_REMOTE: 'true'
      DELUGE_ADD_USER: 'myuser'
      DELUGE_ADD_PASS: 'mypass'

  deluge-web:
    image: keschrich/deluge-web:1.3.15-1
    depends_on:
      - deluged
    links:
      - vpn:deluged
    ports:
      - 8112:8112
    volumes:
      - deluge-web-config:/config
    environment:
      TZ: 'America/New_York'
      DELUGE_USER: 'myuser'
      DELUGE_PASS: 'mypass'

volumes:
  data:
  deluged-config:
  deluge-web-config:
  openvpn:
